# You can find control table of Dynamixel on emanual (http://emanual.robotis.com/#control-table)
# Control table item has to be set Camel_Case and not included whitespace
# You are supposed to set at least Dynamixel ID
# This example is compatible with Dynamixel using protocol 2.0

#Motion

front_left_move:
  ID: 5
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0

front_right_move:
  ID: 7
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0

back_left_move:
  ID: 6
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0

back_right_move:
  ID: 8
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0

#Turning
front_left_turn:
  ID: 2
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0

front_right_turn:
  ID: 3
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0

back_right_turn:
  ID: 4
  Return_Delay_Time: 0
  Operating_Mode: 1
  Profile_Acceleration: 0
  Profile_Velocity: 0

#back_right_turn:
#  ID: 1
#  Return_Delay_Time: 0
#  Operating_Mode: 1
#  Profile_Acceleration: 0
#  Profile_Velocity: 0
